project_id = "itvgzcdcthxqqczqgtbl"

[api]
enabled = true
port = 54321

[db]
enabled = true
port = 54322

[studio]
enabled = true
port = 54323

[functions.chat]
verify_jwt = false

[functions.scam-report]
verify_jwt = false

[functions.url-check]
verify_jwt = false

[functions.ocr-fraud-detection]
verify_jwt = false