// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itvgzcdcthxqqczqgtbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0dmd6Y2RjdGh4cXFjenFndGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDE4MTAsImV4cCI6MjA3MzY3NzgxMH0.K-qPk0o2-T_T99TSpcp7cPP79hEeCeG5KawOVqNk32k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});